# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'FreeChat' do
	pod 'ChatKit'
	pod 'AVOSCloudSNS'
	pod 'AVOSCloudCrashReporting'
end

target 'FreeChatTests' do

end

